migrate_plus.migration_group.*:
  type: config_entity
  label: 'Migration Group'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    source_type:
      type: string
      label: 'Source type'
    module:
      type: string
      label: 'Dependent module'
    shared_configuration:
      type: ignore
      label: 'Shared migration configuration'
