<?php

/**
 * Implements hook_enable().
 */
function devel_enable() {
  // New module weights in core: put devel as the very last in the chain.
  module_set_weight('devel', 88);
}

/**
 * Implements hook_uninstall().
 */
function devel_uninstall() {
  // Delete the development menu.
  if (\Drupal::moduleHandler()->moduleExists('menu')) {
    if ($devel_menu = menu_load('devel')) {
      $devel_menu->delete();
    }
  }
}

